### PR TITLE
two L1 (input) trigger rate modules

### PR DESCRIPTION
**Pull request by andreh12**
towards implementing #139 : here is a proposal for a new class `VeryHighTcdsInputRate` which
* checks the TCDS input trigger rate (sum of trigger rate and suppressed trigger rate)
* if above the 'very high' configurable threshold instructs the shifter to talk to the L1 shifter checking for noisy towers and failed links in the trigger system.

Could please have a quick look (@gladky / @mommsen ) ?

The name of the module may be a bit long.

Later I propose to essentially clone this module and have a second one with different descriptions and actions for 'high' (but not very high) TCDS input trigger rate.

This module checks the sum of trigger and suppressed trigger rates from the TCDS 1HZ flashlist as opposed to `RateTooHigh` which checks the readout rate (which may never go much beyond 100 kHz). 

I propose to add these two modules based on the TCDS input rate in addition to `RateTooHigh` and eventually retire `RateTooHigh` rather than changing the name and functionality of `RateTooHigh`.

### CODE REVIEW

**Comment by gladky** [comment]
The DAQAggregator [1.17.6](https://github.com/cmsdaq/DAQAggregator/commits/release/1.17.6) with instantaneous rate has been deployed to dev instance and its available from our internal maven repository. You can bring it with:

```
<dependency>
	<groupId>ch.cern</groupId>
	<artifactId>DAQAggregator</artifactId>
	<version>1.17.6</version>
</dependency>
```

For the LMs: should we fire this LM always regardless DAQ state or whether we are running or not? I have also one minor suggestion - to set title to "Very high TCDS trigger input rate" instead of "TCDS trigger input rate very high".

**Comment by andreh12** [comment]
I updated the `DAQAggregator` dependency in `pom.xml` by taking it from commit `d849c80` (so it is in the same place in the file). I tested that merging my branch for this pull request with `feature/hlt-check` does not produce any conflicts.

**Comment by andreh12** [comment]
`git cherrypick`ed 1a591c8 from #148 to avoid conflict with this pull request.

**Comment by andreh12** [comment]
now also the two new modules to `LogicModuleRegistry`. Please check the usefulnes values !

* `mvn test` reports: `Tests run: 130, Failures: 0, Errors: 0, Skipped: 20`
* `mvn integration-test` reports: `Tests run: 11, Failures: 0, Errors: 0, Skipped: 3`

Ready to merge in my opinion (but probably better to wait until #148 is merged).

**Comment by gladky** [comment]
@hsakulin suggested to avoid running 'high rate' when 'very high rate' is satisfied.

**Comment by gladky** [comment]
@andreh12  Title "Very high TCDS trigger input rate" is too long for our current schema. The limitation is 30 chars for the title. The title proposed is 33 chars. This limitation is driven by 3 reasons:

1. the title in the dashboard is quite big
2. the title in the  browser should fit without the necessity to zoom a lot
3. it should give brief idea of what's the problem - for more details there is the description field that is limited to 4000 characters.

Having this mentioned I would propose not to alter the limitation for the title in schema but shorten a title a bit. Can I shorten the title for this LM to "Very high trigger input rate"? If you have other proposal please let me know.

**Comment by andreh12** [comment]
yes, please change the title as you suggested

**Pull request merged**
